package gov.cabinetoffice.shared.enums;

public enum EventType {

    ADVERT_CREATED,
    ADVERT_UPDATED,
    ADVERT_PUBLISHED,

    APPLICATION_CREATED,
    APPLICATION_UPDATED,
    APPLICATION_PUBLISHED,

    SUBMISSION_CREATED,
    SUBMISSION_UPDATED,
    SUBMISSION_PUBLISHED

}
